### ISSUE TITLE
How i can highlight the tooltip item widget .if only text there

### ISSUE THREAD

**Issue by swapnilsinha17** [Deuque/overlay_tooltip#4]
<img width="204" alt="Screenshot 2022-03-29 at 12 41 33 PM" src="https://user-images.githubusercontent.com/52417551/160554229-597f3d85-ef2a-4c10-a026-c7bf614d2ad2.png">

**Comment by swapnilsinha17** [comment]
@Deuque Please help

**Comment by Deuque** [comment]
> <img alt="Screenshot 2022-03-29 at 12 41 33 PM" width="204" src="https://user-images.githubusercontent.com/52417551/160554229-597f3d85-ef2a-4c10-a026-c7bf614d2ad2.png">

You can give the text a white background (or a color that matches your screen background) so it stays visible even when highlighted.
Improvements will be made so you can add custom background layouts for your widgets when they are highlighted.
