### ISSUE TITLE
How to use multiple TooltipControllers in one screen?

### ISSUE THREAD

**Issue by danoetz** [Deuque/overlay_tooltip#5]
Can we add more than one TooltipController in one screen? So we can add multiple tooltip section. 
For example:
- **Button A** will trigger `Tooltip 1` with `3 OverlayTooltipItem` inside. 
- **Button B** will trigger `Tooltip 2` with another `2 OverlayTooltipItem` inside.

**Comment by Deuque** [comment]
Sure you can, but the buttons and tooltips will be contained in separate overlayScaffolds, like this: <br/>
<img width="374" alt="Untitled" src="https://user-images.githubusercontent.com/38636261/177704397-2b6e927f-684e-4044-90c1-51f604e35978.png">

However, improvements can be made to how controllers work, to enable you pause and continue from whatever index you want.

**Comment by Deuque** [comment]
@danoetz version 0.2.0 now includes the `pause` capability and the ability to start tooltip at any index using `start(<index>)`. <br/>
Hopefully this helps you pause your tooltips after the first set of tooltips are shown, and continue at the right index when the second button is clicked, all using the same controller.

**Comment by danoetz** [comment]
Is it possible to be nested OverlayTooltipScaffold?

Just now I'm updating to v0.2.0, and got this error:
 `.pub-cache/hosted/pub.dartlang.org/overlay_tooltip-0.2.0/lib/src/core/overlay_tooltip_item.dart:42:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.`

**Comment by Deuque** [comment]
@danoetz it seems you have an old version of flutter, you can try updating your flutter sdk by running `flutter upgrade`, that should fix the null warning

**Comment by Deuque** [comment]
> Is it possible to be nested OverlayTooltipScaffold?<br/>
>
Yes its possible,

**Comment by danoetz** [comment]
![Screen Shot 2022-07-20 at 12 55 10](https://user-images.githubusercontent.com/4177312/179907198-c96e9473-9ff9-44d2-8036-31a1e7933b8e.png)

I'm using flutter v2.10.5

**Comment by Deuque** [comment]
v0.2.1 has been released with the null fix.<br/>
Side note, I would recommend upgrading to the latest flutter version (3.0.4),
