### ISSUE TITLE
child  item overlay tooltip  not  highlighted

### ISSUE THREAD

**Issue by ramaagusdwi** [Deuque/overlay_tooltip#8]
i have been implemented this library but my child widget is not highligted 

this my screen shoot 
![SS 11](https://user-images.githubusercontent.com/17122961/180427278-7d206e05-aa5c-4a32-877d-2e9c455e20e7.jpg)

**Comment by Deuque** [comment]
Please share details on how you implemented it, a code screenshot maybe

**Comment by ramaagusdwi** [comment]
im sory, its my mistake,  after change color background in child OverlayTooltipItem it works
