### ISSUE TITLE
[Feature] Provide onTap callback to overlay

### ISSUE THREAD

**Issue by prateekgoel** [Deuque/overlay_tooltip#9]
I have a requirement where i do not have next buttons, I want to be able to move to the next item on click of the overlay. It would be great if the overlay accepts an onTap callback so that I can call controller.next()

**Comment by Deuque** [comment]
@prateekgoel a bit late, but in version 0.2.2 you can now add a custom overlay widget to the OverlayScaffold, which can be a GestureDetector in your case, and then you can detect any gestures necessary.
